export type RoastLevel = 'light' | 'medium-light' | 'medium' | 'medium-dark' | 'dark';
export type CoffeeType = 'single-origin' | 'blend';

export interface BlendComponent {
  /** e.g. "Ethiopia Yirgacheffe" */
  origin: string;
  /** 0–100; all components in a blend must sum to 100 */
  percentage: number;
}

/**
 * A fully persisted coffee entry, including system-generated fields.
 */
export interface CoffeeEntry {
  /** UUID v4, generated by crypto.randomUUID() */
  id: string;
  /** e.g. "Brazilian Santos" — required, max 100 chars */
  name: string;
  /** e.g. "Light Roast, Brazil" — optional */
  origin: string | null;
  /** integer 1–30 inclusive */
  grindLevel: number;
  /** positive float, e.g. 19.0 */
  doseGrams: number;
  /** positive integer, e.g. 35 */
  brewTimeSeconds: number;
  /** free text tasting notes — optional, max 1000 chars */
  notes: string | null;
  /** integer 1–5 or null if unrated */
  rating: number | null;
  /** roast level — null if not set */
  roastLevel: RoastLevel | null;
  /** single-origin or blend — null if not set */
  coffeeType: CoffeeType | null;
  /** blend components; empty array when single-origin or unset */
  blendComponents: BlendComponent[];
  /** flavor descriptors e.g. ["Nutty", "Chocolate"] */
  flavorNotes: string[];
  /** ISO 8601 date of roast, e.g. "2024-01-15" — null if unknown */
  roastedAt: string | null;
  /** ISO 8601 timestamp */
  createdAt: string;
  /** ISO 8601 timestamp */
  updatedAt: string;
}

/**
 * The shape of form data submitted when creating or editing an entry.
 * Omits system-generated fields (id, createdAt, updatedAt).
 */
export interface CoffeeEntryPayload {
  name: string;
  origin: string | null;
  grindLevel: number;
  doseGrams: number;
  brewTimeSeconds: number;
  notes: string | null;
  rating: number | null;
  roastLevel: RoastLevel | null;
  coffeeType: CoffeeType | null;
  blendComponents: BlendComponent[];
  flavorNotes: string[];
  roastedAt: string | null;
}
